before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XTajlaVOFEo7Gl+CYPneVB5BueRwfhTctDLd76FH2t34iT8aQzZ4LUrI8Dt3TMp6vPmQvay8k4a9Cv92pi7oOiDoNf+MeKHEVsbPlVufD8OIW8Z489s06nfYi0ec4WZjbb7aSZbE8mq2FDk8l9wpyFM1426RB4b8c21kYQaqmgraChhz90nJmMHWWzyh2Wj/3vwpKqEhjwGu0NGCZx6GJ8QnRSmSkbLCd4KwVYyNUpET9Qhq3DolKxAPCjEFUFK2hRJ3A//ch5uZxOTsRXVoPP7onTU8niGgzRqpd1lF4LDpBq5+ydIJLmvEPNpjRfxmhwkYJdPr0J+VSifXeCx7bFQ+etfzQuYXOy/yOHH8GxbNp2XngJDmw2FYks8hqm+JD7fEYpo+Ok+B9ek8rjIXrxNO5EsUgxBxUDcq00QvgbY8klZG88hkqNP2NApoe/ZyJcXebXg6xW0bsRZlS5Z4ccpzJfFoJrFx6Un1mfgoXEGeD2qgz1vwbGVu95XaLxITHZJj3wJtKQS/02ze6Bet8BsfkAqAi36U+bh2rauEvDBD8d5GUTdMiLojYjkoI/McuskLN/U6ZAOYZiFLacPK5ZO+FO8zPvbY070Zu2poSfvDRfhPNKIkXyeiRKMOFKhHOZCpsbk4i6eePt7xydfnsNTRyjl7fCn/XhGlOkTvGW8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
